### PR TITLE
finished events card

### PR DESCRIPTION
**Pull request by mck-jacky**

### CODE REVIEW

**Comment by imagine-hussain** [comment]
this is a great start, i've just made a few changes:

- removed `height` and `width` from css; this tends to make conflicts with the images
- If the height / width need to be changed, they can be done w/ inline style
- have made `actions` optional to pass in
- removed the `LandingButton`, i think the `actions` props looks pretty nice

image

This leaves the following changes to be made:
## TODO:
- [ ] move this to common components as `InfoCard`
- [ ] Fix the *default* props; one should expand out the card (can be non-functional for now) and the other should link to somewhere else like FB - this one will use the provided `link`

**Review by imagine-hussain — CHANGES_REQUESTED** [review]
see prev comment for changes

**Comment by mck-jacky** [comment]
hey Hussain, cant reach you in discord:(
I want some clarifications about the task of fixing the default props. Do you mean the setting button should expand out the card and the read more button should link to the provided link?

**Comment by mck-jacky** [comment]
> hey Hussain, cant reach you in discord:( I want some clarifications about the task of fixing the default props. Do you mean the setting button should expand out the card and the read more button should link to the provided link?

**Review by imagine-hussain — APPROVED** [review]

**Pull request merged**
